# Generated by Django 3.2.9 on 2022-05-15 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filehash',
            options={'verbose_name_plural': 'Blockchain'},
        ),
    ]
