# Generated by Django 3.2.9 on 2022-05-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(default=None, null=True, upload_to='blockchain/'),
        ),
    ]
