# Generated by Django 3.2.9 on 2022-05-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0007_auto_20220527_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='filehash',
            name='file_ipfs_hash',
            field=models.TextField(default=None, null=True),
        ),
    ]
