# Generated by Django 3.2.9 on 2022-05-27 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0010_alter_filehash_file_ipfs_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filehash',
            name='file_ipfs_hash',
        ),
    ]
